(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function i(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(s){if(s.ep)return;s.ep=!0;const r=i(s);fetch(s.href,r)}})();const n={form:document.querySelector(".header-form"),list:document.querySelector(".tasks-list"),body:document.body,switch:document.querySelector("#themeToggle")};function a(e,t){const i=JSON.stringify(t);localStorage.setItem(e,i)}function c(e){return JSON.parse(localStorage.getItem(e))}const o="tasksList",u="pageTheme";function m(e,t){return`<li class="task-list-item">
              <button class="task-list-item-btn">Delete</button>
              <h3>${e}</h3>
              <p>${t}</p>
            </li>`}const f=e=>{e.preventDefault();const t={title:e.target.elements.taskName.value,description:e.target.elements.taskDescription.value};if(t.title===""||t.description===""){alert("Enter title and description please!");return}n.list.insertAdjacentHTML("beforeend",m(t.title,t.description));const i=c(o)||[];Array.isArray(i)&&i.push(t),a(o,i),e.target.elements.taskName.value="",e.target.elements.taskDescription.value=""};function h(e){if(e.target.tagName!=="BUTTON")return;const t=e.target.closest(".task-list-item");t.remove();const i=t.children[1].innerText,s=c(o).filter(({title:r})=>r!==i);a(o,s)}function p(){return(c(o)||[]).map(({title:t,description:i})=>`<li class="task-list-item">
              <button class="task-list-item-btn">Delete</button>
              <h3>${t}</h3>
              <p>${i}</p>
            </li>`).join("")}function g(){n.body.classList.contains("theme-dark")?(n.body.classList.replace("theme-dark","theme-light"),a(u,"theme-light")):(n.body.classList.replace("theme-light","theme-dark"),a(u,"theme-dark"))}function L(){const e=c(u);e==="theme-light"&&n.body.classList.replace("theme-dark",e)}n.body.addEventListener("DOMContentLoaded",L());n.list.insertAdjacentHTML("afterbegin",p());n.form.addEventListener("submit",f);n.list.addEventListener("click",h);n.switch.addEventListener("click",g);
//# sourceMappingURL=index.js.map
